### ISSUE TITLE
有关无线网卡白名单的问题

### ISSUE THREAD

**Issue by anran2020** [Moore2253/Install-MacOS-On-Lenovo-G50-70#1]
首先感谢您提供的途径，成功在g50-70m上的装好了montorey。了解了下有关这款笔记本装免驱无线网卡的讯息，目前已经解决了白名单的问题，接下来买个网卡装就好了。不知道您这个无线网卡是不是出厂就带的还是自己换过。

另外，在您发出来的发行版本中只找到clover引导的文件 ，没有看到oc的引导文件，不知道您能否分享，感谢！

**Comment by Moore2253** [comment]
非常感谢你的评论，我的网卡是出厂内置的ar956x，貌似网卡驱动和12有内核冲突，所以我也就没有安装。我没有时间维护GitHub，所以也就没有上传，如有需要，我将过几天上传并且编辑完readme文件，也可以添加联系方式相互讨论，Thank you！

**Comment by anran2020** [comment]
十分感谢您的回复，这是我的邮箱（jujubo659@hotmail.com）
，期待跟你有更多的交流。如果您没有继续维护github打算，您可以通过邮箱分享oc引导文件给我。

因为有使用无线网络的需求，在有成功的引导文件之后，对像我这样的情况，剩下可能就是解决无线网络的问题了（我电脑自带的是瑞昱的网卡），您的回复提到网卡驱动和12内核可能有冲突，我原是打算更换博通免驱网卡，我想这点是比较好的解决了黑苹果无线网络的问题，但因为联想bios有白名单模块限制的问题，16年之前上市的电脑无法直接更换无线网卡，需要通过一些方式删除或修改bios白名单模块才能实现无线网卡的正常使用。如果后续这个项目或者您有需要有关更换无线网卡需要，我很愿意帮忙。

**Comment by Moore2253** [comment]
嘿，兄弟，感谢您的再一次的回复，您的邮箱已经收到，稍后我会把更详细的信息以及efi文件通过邮箱发送给您，再次感谢你的支持！

**Comment by anran2020** [comment]
十分感谢您百忙中抽空给我发了邮件，邮件已经收到，并且在github中下载了您最新分享的efi，感谢！
